apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1883
      name: mqtt
  selector:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
